"""migration

Revision ID: 5f1bf8cf38fd
Revises: 8611a400bafb
Create Date: 2025-03-20 00:04:02.097824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f1bf8cf38fd'
down_revision: Union[str, None] = '8611a400bafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reset_password_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password_tokens',
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], name='reset_password_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name='reset_password_tokens_pkey')
    )
    # ### end Alembic commands ###
