"""add auto increment in uuid user field

Revision ID: b2fb80b5a30a
Revises: 5cf57b0ba59b
Create Date: 2025-02-21 01:52:04.411259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2fb80b5a30a'
down_revision: Union[str, None] = '5cf57b0ba59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
